export const CONFIG = {
  defaultSourceLanguage: "en",
  defaultTargetLanguage: "th",
  recognitionLanguage: "en-US",
  defaultAutoSpeak: false,
  autoSpeakEnabled: true,
  translationEndpoint: "https://translate.fedilab.app/translate",
  myMemoryEndpoint: "https://api.mymemory.translated.net/get",
  googleTranslateEndpoint: "https://translate.googleapis.com/translate_a/single",
  translationRequestTimeoutMs: 10000,
  fastTranslationRequestTimeoutMs: 4000,
  recognitionRestartDelayMs: 300,
  translationApiKeyStorageKey: "voice-translator-api-key",
  translationEndpointStorageKey: "voice-translator-endpoint",
  autoSpeakStorageKey: "voice-translator-auto-speak",
  selectedVoiceStorageKey: "voice-translator-selected-voice",
  toastDurationMs: 3600,
};
